workspaceName: mdsynapsewspace-pro
LS_AKV_properties_typeProperties_baseUrl: https://akv-cicddemo-pro.vault.azure.net/
mdsynapsewspace-WorkspaceDefaultStorage_properties_typeProperties_url: https://mddlakestoragepro.dfs.core.windows.net
