# This is a basic workflow to help you get started with Actions

name: Copy between Table storage 

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "workspace_publish" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs: 
  buildjob:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - run: |
          count=`jq '.blob | length' ./mdsynapsewspace/datamigration.json`
          for ((i=0; i<$count; i++)); do
            bsrc=`jq -r '.table['$i'].source' ./mdsynapsewspace/datamigration.json`
            bdst=`jq -r '.table['$i'].destination' ./mdsynapsewspace/datamigration.json`
            echo "Origen es $bsrc y destino es $bdst"
          done
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Copy between blob storage PRE and PRO
        uses: kheiakiyama/install-azcopy-action@v1
        with:
          version: 'v10'
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - run: azcopy copy -h
      - run: azcopy_v10 cp 'https://mddlakestorage.table.core.windows.net/MDTestTable1' 'https://mddlakestoragepro.table.core.windows.net/MDTestTable1'  
      # Azure logout
      - name: logout
        run: |
          az logout
        if: always()
